[package]
name = "object_store_gzip_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
object_store = { version = "0.11.2", features = ["http"] }
reqwest = { version = "0.12.9", features = ["gzip"] }
tokio = { version = "1.42.0", features = ["full"] }
